export const WORDS = [
  'under', 'couch',
  'mommy', 'chair',
  'warms', 'backs',
  'panda', 'pouch',
  'house', 'light',
  'hippo', 'tummy',
  'couch', 'table',
  'scuba', 'masks',
  'fancy', 'glass',
  'cooks', 'robes',
  'lunch', 'boxes',
  'games', 'shelf',
  'under', 'piano',
  'white', 'stool',
  'faith', 'frame',
  'white', 'humid',
  'nutty', 'craft',
  'under', 'mouse',
  'above', 'blind',
  'small', 'tools',
  'water', 'tides'
]
